apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/eljamo/mempass-api
    newTag: latest

# Enable patching for image tags and ingress host
patches: []
