apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy
spec:
  arguments:
    parameters:
      - name: repo
        value: eljamo/ephemeral-test-environment.git
      - name: branch
        value: main
      - name: path-chart
        value: helm/mempass
      - name: image
        value: ghcr.io/eljamo/mempass:latest
      - name: vcluster-name
        value: demo-deploy
  entrypoint: main
  # We use a volume claim template so that we can have a shared workspace.
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Mi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone-repo
            template: tmpl-clone
            arguments:
              parameters:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
          - name: create-vcluster
            template: tmpl-vcluster
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.vcluster-name}}"
          - name: install-helm-chart
            template: tmpl-deploy
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.vcluster-name}}"
                - name: path-chart
                  value: "{{workflow.parameters.path-chart}}"
                - name: image
                  value: "{{workflow.parameters.image}}"
            depends: "clone-repo && create-vcluster"
    - name: tmpl-clone
      inputs:
        parameters:
          - name: repo
          - name: branch
      container:
        image: alpine/git:v2.26.2
        workingDir: /work
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: GH_TOKEN # name of env var
            valueFrom:
              secretKeyRef:
                name: github-token # name of an existing k8s secret
                namespace: argo
                key: token
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{inputs.parameters.branch}}"
          - --single-branch
          - "https://workflow:$(GH_TOKEN)@github.com/{{inputs.parameters.repo}}"
          - ./ # never change this to just a . it doesn't work
        volumeMounts:
          - name: work
            mountPath: /work
    - name: tmpl-vcluster
      inputs:
        parameters:
          - name: name
      container:
        image: ghcr.io/loft-sh/vcluster-cli:0.23
        command:
          - vcluster
        args:
          - create
          - "{{inputs.parameters.name}}"
          - --namespace
          - "{{workflow.parameters.vcluster-name}}"
          - --connect=false
    - name: tmpl-deploy
      inputs:
        parameters:
          - name: name
          - name: path-chart
          - name: image
      container:
        volumeMounts:
          - mountPath: /work
            name: work
        image: ghcr.io/loft-sh/vcluster-cli:0.23
        workingDir: /work/{{inputs.parameters.path-chart}}
        command:
          - vcluster
        args:
          - connect
          - "{{inputs.parameters.name}}"
          - --namespace
          - "{{workflow.parameters.vcluster-name}}"
          - --
          - helm
          - upgrade
          - --install
          - "{{inputs.parameters.name}}"
          - ./ # never change this to just a . it doesn't work
          - --namespace
          - "{{inputs.parameters.name}}"
          - --create-namespace
