apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: destroy
spec:
  arguments:
    parameters:
      - name: deployment-name
        value: deployment-name
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: delete-vcluster
            template: tmpl-delete-vcluster
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.deployment-name}}"
    - name: tmpl-delete-vcluster
      inputs:
        parameters:
          - name: name
      container:
        image: ghcr.io/loft-sh/vcluster-cli:0.19
        command:
          - vcluster
        args:
          - delete
          - "{{inputs.parameters.name}}"
          - --namespace
          - "{{workflow.parameters.deployment-name}}"
          - --auto-delete-namespace
          - --delete-namespace
